#!/bin/bash
lock() {
#    i3lock -i ~/Pictures/Screenshotfrom2015-01-1913\:17\:35.png -u -p win
#    i3lock -i ~/.i3/lockscreen.png -t -c 667676 -u -p win
    i3lock -c 666666 -u -p win
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
