#!/bin/bash

#depends on: imagemagick, i3lock, scrot

IMAGE=/tmp/lockscreen.png
TEXT=/tmp/locktext.png
ICON=~/.i3/Lock.png
rm $TEXT
MSG=$(fortune | tr '\n' '_' | sed 's/_/\\n/g')
scrot $IMAGE
convert $IMAGE -scale 10% -scale 1000% -fill black -colorize 25% $IMAGE
[ -f $TEXT ] || { 
    convert -size 1000x450 xc:white -font Liberation-Sans -pointsize 26 -fill black -gravity center -annotate +0+0 ''"$MSG"'' $TEXT;
    convert $TEXT -alpha set -channel A -evaluate set 50% $TEXT; 
}
convert $IMAGE $TEXT -gravity west -geometry +390+0 -composite $IMAGE
convert $IMAGE $ICON -gravity northeast -composite -matte $IMAGE
convert $IMAGE $ICON -gravity southeast -composite -matte $IMAGE
convert $IMAGE $ICON -gravity northwest -composite -matte $IMAGE
convert $IMAGE $ICON -gravity southwest -composite -matte $IMAGE
i3lock -u -i $IMAGE
